title: Portfolio
author: © 2026 Zachary Shiner
baseurl: "" # the subpath of your site, e.g. /blog
url: "zcshiner.github.io"
repository: "zcshiner/zcshiner.github.io"

linkedin_username:  zcshiner
github_username: zcshiner

markdown: kramdown
remote_theme: "jekyll/minima@c6e74bb"

plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /projects/:title

header_pages:
    - index.md
    - projects.md
    - photography.md
    - patents.md
    - contact.md

exclude:
    - CLAUDE.md
    - Dockerfile
    - README.md
