title: Portfolio
author: © 2026 Zachary Shiner
description: >-
  Write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "zcshiner.github.io" # the base hostname & protocol for your site, e.g. http://example.com

linkedin_username:  zcshiner
github_username: zcshiner

markdown: kramdown
# theme: minima
# remote_theme: "jekyll/minima@1e8a445"
remote_theme: "jekyll/minima@c6e74bb"

plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /posts/:title

header_pages:
    - index.md
    - projects.md
    - patents.md
    - contact.md

exclude:
    - CLAUDE.md
    - Dockerfile
    - README.md
